[config]
default_to_workspace = false


[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy]
toolchain = "stable"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.lint]
run_task = [
    { name = ["clippy"] },
]
dependencies = ["fmt-check"]

[tasks.lint-test]
toolchain = "stable"
command = "cargo"
args = ["test"]
dependencies = ["lint"]
